---
title: 异常
date: 2022-01-12 17:56:18
permalink: /pages/ac2952/
categories:
  - 后端
  - Java基础
  - Java
tags:
  - 
---
# 异常体系
异常的根类是: Throwable 有两个子类 Error和 Exception,平时所说的异常是指 Exception
java.lang.Throwable 是Java语言中所有错误或异常的超类

## Exception
Exception 是编译期异常,进行编译时出的问题
### RuntimeException
RuntimeException 运行期异常,java程序运行期间出现的问题
> 异常相当于程序得了一个小毛病,把异常处理掉,程序可以继续执行

## Error
> Error就相当于程序得了一个无法治愈的病(癌症),就必须修改代码,程序才能继续执行

## Throws 抛出异常的声明
> throws是方法可能抛出异常的声明。(用在声明方法时，表示该方法可能要抛出异常)

语法：`修饰符 返回值类型 方法名 参数列表 throws 异常类  {......}`
``` java
 public void doA(int a) throws Exception1,Exception3{......}
```
## Throw 抛出异常
> 使用 throw new 一个异常("提示语")

## 二者区别
throws E1,E2,E3只是告诉程序这个方法可能会抛出这些异常，方法的调用者可能要处理这些异常，而这些异常E1，E2，E3可能是该函数体产生的。

throw则是明确了这个地方要抛出这个异常
```java
 void doA(int a) throws IOException,{
    try{
        ....
    }catch(Exception1 e){
        throw e;
    }catch(Exception2 e){
        System.out.println("出错了！");
    }
    if(a!=b){
        throw new  Exception3("自定义异常");
    }
}
 ```

代码块中可能会产生3个异常，(Exception1,Exception2,Exception3)。

如果产生Exception1异常，则捕获之后再抛出，由该方法的调用者去处理。

如果产生Exception2异常，则该方法自己处理了（即System.out.println("出错了！");）。所以该方法就不会再向外抛出Exception2异常了，void doA() throws Exception1,Exception3 里面的Exception2也就不用写了。

而Exception3异常是该方法的某段逻辑出错，程序员自己做了处理，在该段逻辑错误的情况下抛出异常Exception3，则该方法的调用者也要处理此异常。


throw语句用在方法体内，表示抛出异常，由方法体内的语句处理。

throws语句用在方法声明后面，表示再抛出异常，由该方法的调用者来处理。

throws主要是声明这个方法会抛出这种类型的异常，使它的调用者知道要捕获这个异常。

throw是具体向外抛异常的动作，所以它是抛出一个异常实例。
 
throws说明你有那个可能，倾向。

throw的话，那就是你把那个倾向变成真实的了。

 

同时：

1、throws出现在方法函数头；而throw出现在函数体。

2、throws表示出现异常的一种可能性，并不一定会发生这些异常；throw则是抛出了异常，执行throw则一定抛出了某种异常。

3、两者都是消极处理异常的方式（这里的消极并不是说这种方式不好），只是抛出或者可能抛出异常，但是不会由函数去处理异常，真正的处理异常由函数的上层调用处理。

## 捕获异常
### try catch
try{}catch(Exception e){}

e.getMessage()// 获取异常信息
e.toString()// 重写了toString方法,打印具体信息

### try catch finally
try{}catch(Exception e){}finally {}

### 注意事项
1. 一次捕获,多次处理
2. 一次捕获,一次处理
3. 多次捕获,多次处理

> 在finally中不要使用return 否则永远会抛出finally中的return



## 自定义异常
自定义异常类一般都是以Exception结尾,说明类是一个异常类
2. 自定义异常类,必须继承Exception或者RuntimeException

继承 Exception:name自定义的异常类就是一个编译器异常,如果方法内部抛出编译器异常,就必须处理
继承 RuntimeException name自定义异常类就是一个运行期异常,无需处理,交个虚拟机处理(中断处理)



